---
title: "Assignment 4"
author: "Kai Lukowiak, Jann Bernberg"
date: '2018-07-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Loading Libraries:


```{r, warning=F, message=F}
library(tidyverse)
library(recommenderlab)
```

# Data
We are just going to use regular data contained in the MovieLense set. 


```{r}
data(MovieLense)
class(MovieLense)
```

```{r}
image(MovieLense, main = "Heatmap of the rating matrix")
```


# Temp Predictions


```{r}
xval <- evaluationScheme(MovieLense, 
                         method = "split", 
                         train = 0.7, 
                         given = 3,
                         goodRating = 5)

xval
```



Convert ratingsMatrix to data.frame

```{r}
rm_svd <- Recommender(data = getData(xval, "train"), 
                       method = "SVD")
p1 <- predict(rm_svd, getData(xval, "train"), type = "ratingMatrix")
p2 <- predict(rm_svd, getData(xval, "known"), type = "ratingMatrix")
p3 <- predict(rm_svd, getData(xval, "unknown"), type = "ratingMatrix")
```


```{r}
temp1 <- as(p1, 'data.frame')
temp2 <-  as(p2, 'data.frame')
temp3 <-  as(p3, 'data.frame')
```



```{r}
svdPred <- rbind(temp1, temp2)
dim(svdPred)
svdPred %>% head()
svdPred <- svdPred %>% spread(key = item, value = rating)
dim(svdPred)
```



I think we can delete this?


```{r}
narrowDF <- as(MovieLense, 'data.frame')
narrowDF %>% head()
wideDF <- spread(data = narrowDF, key = item, value = rating)
wideDF[1:10, 1:10]
```

We need to get the userID and Movie Name for these ratings so that we can index them for our predictions.

```{r}
userID <- wideDF$user
movieNames <- names(wideDF)[2:dim(wideDF)[2]]
```



```{r}
similarity_users <- similarity(MovieLense, method = "pearson", which = "users")

```

```{r}
pearsonMat = as.matrix(similarity_users) %>% 
  as_data_frame() 

names(pearsonMat) = userID
pearsonMat$user <- userID
pearsonMat %>% head()
```


```{r}
library(reshape2)
pearsonMatNarrow <- pearsonMat %>% 
  melt('user' )
pearsonMatNarrow %>% head()
```



```{r}
simUser <- function(uid, df){
  top20 = df %>% 
    filter(user == uid & value != 1) %>%  # Necessary to remove perfectly correlated. (Check if this is the case)
    arrange(desc(value)) %>% 
    na.omit() %>% 
    head(20)
  return(top20)
}

simUser(1, pearsonMatNarrow)
```

This filters the relevant user and orders them by similarity.


```{r}
mean20 <- function(userList, df, minRating = 4){
  top20 <- df[userList, ] %>% select(-user)
  top20Mat = as.matrix(as.data.frame(lapply(top20, as.numeric))) # R is weird.
  
  itemMeans <- colMeans(top20Mat, na.rm = TRUE)
  meanDF <- data_frame(names(top20), itemMeans, )
  colnames(meanDF) <- c('itemId', 'rating')
  meanDF <- meanDF %>% 
    filter(rating > minRating) %>% #
    arrange(desc(rating)) # This must be
  return(meanDF)
}

test <- simUser(1, pearsonMatNarrow)
meanDF <- mean20(userList = test$variable, wideDF)
```





```{r}
numRatings <- function(mat){
  # Takes a sparse matrix and counts non-na values.
  temp <- sapply(mat, function(x) sum(is.na(x)))
  temp <- data_frame(names(temp), temp)
  names(temp) <- c('itemId', 'count')
  return(temp)
}
numRatingsList <- numRatings(select(wideDF, -user))

```


```{r}
innerJoiner <- function(rankList, meanDF){
  inner_join(rankList, meanDF, by = 'itemId' )
  rankList <- rankList %>% 
    arrange(desc(count)) %>% 
    head(10)
  return(rankList)
}
innerJoiner(numRatingsList, meanDF)
```


```{r}
serRecs <- function(rankList, mat, uId){
  itemsToChange = rankList$itemId
  mat[uId, itemsToChange] = 5
  return(mat)
}


```


```{r}
aggrigator <- function(uID, matToChange, wideDF, pearsonMatNarrow, rankList){
  simUserIDS <- simUser(uID, pearsonMatNarrow)
  avg20 <- mean20(uID, wideDF)
  topN <- innerJoiner(rankList,avg20)
  ret <- serRecs(topN, matToChange, uID)
  return(ret)
}

testMAt <- aggrigator(uID = 1, matToChange = svdPred, 
                      wideDF = mat2,  pearsonMatNarrow = pearsonMatNarrow, rankList = numRatingsList)
```


```{r}
svdPred1 <- svdPred
for (i in wideDF$user) {
  svdPred1 <- aggrigator(uID = i, 
             matToChange = svdPred1,  
             wideDF = mat2,  
             pearsonMatNarrow = pearsonMatNarrow, 
             rankList = numRatingsList)
}
```



To Delete
```{r}

simUser(1, pearsonMatNarrow) # where 1 is uid

test <- simUser(1, pearsonMatNarrow)
mean20(userList = test$variable, wideDF)
numRatingsList

innerJoiner(numRatingsList, meanDF)
```

